env:
  global:
    - XDEBUG_MODE=coverage

language: php

php:
 - '7.2'
 - '7.3'
 - '7.4'

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer update

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c ./tests/phpunit.xml
  - vendor/bin/psalm --shepherd

after_success:
  - travis_retry vendor/bin/php-coveralls
  - travis_retry vendor/bin/infection --threads=4 --log-verbosity=none
